
var isPowers = [{
        "rank": 20000,
        "name": "Hide",
        "ico": "",
        "kick": 1,
        "delbc": 1,
        "alert": 1,
        "mynick": 1,
        "unick": 1,
        "ban": 1,
        "publicmsg": 1,
        "forcepm": 1,
        "roomowner": 1,
        "createroom": 1,
        "rooms": 1,
        "edituser": 1,
        "setpower": 1,
        "upgrades": 1,
        "history": 1,
        "cp": 1,
        "stealth": 1,
        "owner": 1,
        "meiut": 1,
        "loveu": 1,
        "ulike": 1,
        "bootedit": 1,
        "flter": 1,
        "subs": 1,
        "shrt": 1,
        "msgs": 1,
        "broadcast": 1,
        "camera": 1,
        "grupes": 1,
        "delmsg": 1,
        "delpic": 1
    },
	{
        "rank": 10000,
        "name": "chatmaster",
        "ico": "",
        "kick": 1,
        "delbc": 1,
        "alert": 1,
        "mynick": 1,
        "unick": 1,
        "ban": 1,
        "publicmsg": 1,
        "forcepm": 1,
        "roomowner": 1,
        "createroom": 1,
        "rooms": 1,
        "edituser": 1,
        "setpower": 1,
        "upgrades": 1,
        "history": 1,
        "cp": 1,
        "stealth": 1,
        "owner": 1,
        "meiut": 1,
        "loveu": 1,
        "ulike": 1,
        "bootedit": 1,
        "flter": 1,
        "subs": 1,
        "shrt": 1,
        "msgs": 1,
        "broadcast": 1,
        "camera": 1,
        "grupes": 1,
        "delmsg": 1,
        "delpic": 1
    },
	{
        "rank": 9999,
        "name": "gochat",
        "ico": "",
        "kick": 1,
        "delbc": 1,
        "alert": 1,
        "mynick": 1,
        "unick": 1,
        "ban": 1,
        "publicmsg": 1,
        "bootedit": 1,
        "forcepm": 1,
        "roomowner": 1,
        "createroom": 1,
        "rooms": 1,
        "edituser": 1,
        "setpower": 1,
        "upgrades": 1,
        "history": 1,
        "cp": 1,
        "stealth": 1,
        "owner": 1,
        "meiut": 1,
        "loveu": 1,
        "ulike": 1,
        "flter": 1,
        "subs": 1,
        "shrt": 1,
        "msgs": 1,
        "broadcast": 1,
        "camera": 1,
        "grupes": 1,
        "delmsg": 1,
        "delpic": 1
    }
]


module.exports = isPowers;
